live_config_reload = true

import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "alacritty"

[font]
size = 18.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"
